<content class="container row" style="">
	<h1 class="ash-margin">Prime Minister Launches Bursa’s Leap Market</h1>
	<div style="padding: 30px">
		<center><img src="http://www.thestar.com.my/~/media/online/2017/07/25/18/47/p1_bizd_pg1_july26_ky_1.ashx/?w=620&h=413&crop=1&hash=5A6032063A7D35EFF5208DB1C2C14FEC322C0887"></center>
		<br>
		<p>KUALA LUMPUR: Prime Minister Datuk Seri Najib Tun Razak officially launched Bursa Malaysia’s Leading Entrepreneur Accelerator Platform (Leap) Market at Invest Malaysia Kuala Lumpur 2017 here yesterday.</p><span id="innity-in-post"></span><p>The new market aims to provide small and medium enterprises (SMEs) with an alternative and efficient fund-raising platform and visibility through the capital market. </p><p>With the addition of the Leap Market, the three markets on Bursa Malaysia would create a complete range of investment opportunities in the country. </p><p>“The Leap market is an alternative capital-raising platform for SMEs and it is the first of its kind in Asean. </p><div class="inlineAdMobile">
		<p>“It is designed to address the funding gap for SMEs and make it easier for them to take their businesses to the next level through raising funds in the capital market. It also provides them with a new investable asset class,” Bursa Malaysia chief executive officer Datuk Seri Tajuddin Atan said. </p><p>Tajuddin said the availability of the Leap platform would further aid the development of SMEs and support broader economic activities. </p><p>Trading on the Leap Market, however, would be limited to sophisticated investors, according them with an opportunity to broaden their investment options in a transparent and regulated environment.</p><p>During the launch, Najib also witnessed the exchange of memorandum of understanding between Bursa Malaysia and its four strategic partners – Malaysia Digital Economy Corp, Malaysia Technology Development Corp, SME Corp and Unit Peneraju Agenda Bumiputera. </p><p>The strategic partners would support the identification of potential SMEs to be listed on the Leap Market as well as collaborate to jointly develop the SME financing ecosystem and capacity building. </p><p>Najib said the launch of the Leap Market was in line with the government’s SME Masterplan, which aims to raise the share of gross domestic product contributed by SMEs, their number of employees, and their export volume. </p><p>“It is another of the many initiatives that my government has put in place in pursuit of our transformation, and that proves our trustworthiness as the business-friendly government of a vibrant economy,” Najib added. </p><p>SMEs at present make up 97% of businesses in Malaysia. </p><p>To date, 11 SMEs have engaged approved advisers to assist them with the listing process on the Leap Market. These potential issuers are Cloudaron Pte Ltd, Agrofresh International Group Sdn Bhd, Red Ideas Holdings Sdn Bhd, Polymer Link Sdn Bhd, Trustgate Bhd, Accent Wellness Global Sdn Bhd, East West One Group Sdn Bhd, Macfeam Sdn Bhd, Upstream Downstream Process &amp; Services Sdn Bhd, ProEight Sdn Bhd and Safetyware Sdn Bhd.</p><p>Meanwhile, Malaysian Associated Indian Chambers of Commerce and Industry president Tan Sri Kenneth Eswaran said Leap is ideal for SMEs, which are currently underserved in the market.</p><p>“This programme allows them to raise funds and enhance their profile in an efficient and cost-effective way,” he said.</p><p>“Currently, 96% of SME funding comes from the banking sector while the remaining 4% is from the capital market.</p><p>Kenneth commended Prime Minister Datuk Seri Najib Tun Razak, who launched Leap yesterday, for his constant support of and encouragement to SMEs in the country.</p><p>He added that Leap is part of the SME Masterplan which aims to raise the share of gross domestic product contributed by SMEs, the number of employees and export volume, which is in line with Najib’s vision of turning Malaysia into a gateway to Asean and the region.</p>
	</div>
</content>




